// frontend/src/components/Layout/Sidebar.tsx
import React from 'react';
import { Home, Disc, User, Settings, ScanLine, BarChart2 } from 'lucide-react';
import { useNavigate, useLocation } from 'react-router-dom';

interface SidebarProps {
  onScanClick?: () => void;
}

const NavItem = ({
  path,
  icon: Icon,
  label,
  isActive,
  navigate,
}: {
  path: string;
  icon: React.ElementType;
  label: string;
  isActive: boolean;
  navigate: ReturnType<typeof useNavigate>;
}) => (
  <button
    onClick={() => navigate(path)}
    className={`flex flex-col items-center justify-center py-4 px-2 w-[calc(100%-1rem)] rounded-2xl mx-2 transition-all duration-200 ${
      isActive
        ? 'text-indigo-600 dark:text-indigo-400 bg-indigo-50/50 dark:bg-indigo-900/20 shadow-sm'
        : 'text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-100/50 dark:hover:bg-slate-800/50'
    }`}
  >
    <Icon size={26} strokeWidth={isActive ? 2.5 : 2} className={isActive ? 'drop-shadow-sm' : ''} />
    <span className={`mt-1.5 text-xs tracking-wide ${isActive ? 'font-bold' : 'font-medium'}`}>
      {label}
    </span>
  </button>
);

const Sidebar: React.FC<SidebarProps> = ({ onScanClick }) => {
  const navigate = useNavigate();
  const location = useLocation();

  const isActive = (path: string) => location.pathname === path;

  return (
    <aside className="hidden md:flex flex-col w-24 h-[calc(100vh-4rem)] bg-white/60 dark:bg-slate-900/60 backdrop-blur-xl fixed left-0 top-16 border-r border-slate-200/50 dark:border-slate-700 z-20 items-center py-6 transition-colors shadow-[4px_0_24px_-12px_rgba(0,0,0,0.05)]">
      <nav className="flex-1 flex flex-col gap-4 w-full">
        <NavItem path="/" icon={Home} label="Home" isActive={isActive('/')} navigate={navigate} />
        <NavItem
          path="/collection"
          icon={Disc}
          label="Collection"
          isActive={isActive('/collection')}
          navigate={navigate}
        />
        <NavItem
          path="/statistics"
          icon={BarChart2}
          label="Stats"
          isActive={isActive('/statistics')}
          navigate={navigate}
        />
        <NavItem
          path="/profile"
          icon={User}
          label="Profile"
          isActive={isActive('/profile')}
          navigate={navigate}
        />

        <div className="px-3 mt-4 w-full">
          <button
            onClick={onScanClick}
            className="flex flex-col items-center justify-center py-3.5 w-full bg-indigo-500 text-white rounded-2xl shadow-[0_8px_16px_-6px_rgba(79,70,229,0.5)] hover:bg-indigo-600 hover:-translate-y-1 transition-all duration-300 group"
            aria-label="Scan Record"
          >
            <ScanLine size={24} className="group-hover:scale-110 transition-transform" />
            <span className="mt-1.5 text-xs font-bold tracking-wide">Scan</span>
          </button>
        </div>
      </nav>

      <button
        onClick={() => navigate('/settings')}
        className="p-4 text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-300 transition-colors rounded-xl hover:bg-slate-100/50 dark:hover:bg-slate-800/50 mb-2"
      >
        <Settings size={24} />
      </button>
    </aside>
  );
};

export default Sidebar;

// frontend/src/app/shared/components/layout/sidebar/sidebar.component.ts
import { Component, output } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import {
  LucideHome,
  LucideDisc,
  LucideUser,
  LucideSettings,
  LucideScanLine,
  LucideBarChart2,
} from '@lucide/angular';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [
    RouterLink,
    RouterLinkActive,
    LucideHome,
    LucideDisc,
    LucideUser,
    LucideSettings,
    LucideScanLine,
    LucideBarChart2,
  ],
  template: `
    <aside
      class="hidden md:flex flex-col w-24 h-[calc(100vh-4rem)] bg-white/60 dark:bg-slate-900/60 backdrop-blur-xl fixed left-0 top-16 border-r border-slate-200/50 dark:border-slate-700 z-20 items-center py-6 transition-colors shadow-[4px_0_24px_-12px_rgba(0,0,0,0.05)]"
    >
      <nav class="flex-1 flex flex-col gap-4 w-full">
        <!-- Home -->
        <a
          routerLink="/"
          [routerLinkActiveOptions]="{ exact: true }"
          routerLinkActive
          #rlaHome="routerLinkActive"
          [class]="
            'flex flex-col items-center justify-center py-4 px-2 w-[calc(100%-1rem)] rounded-2xl mx-2 transition-all duration-200 ' +
            (rlaHome.isActive
              ? 'text-indigo-600 dark:text-indigo-400 bg-indigo-50/50 dark:bg-indigo-900/20 shadow-sm font-bold'
              : 'text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-100/50 dark:hover:bg-slate-800/50 font-medium')
          "
        >
          <svg lucideHome [size]="26" [strokeWidth]="rlaHome.isActive ? 2.5 : 2"></svg>
          <span class="mt-1.5 text-xs tracking-wide">Home</span>
        </a>

        <!-- Collection -->
        <a
          routerLink="/collection"
          routerLinkActive
          #rlaCol="routerLinkActive"
          [class]="
            'flex flex-col items-center justify-center py-4 px-2 w-[calc(100%-1rem)] rounded-2xl mx-2 transition-all duration-200 ' +
            (rlaCol.isActive
              ? 'text-indigo-600 dark:text-indigo-400 bg-indigo-50/50 dark:bg-indigo-900/20 shadow-sm font-bold'
              : 'text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-100/50 dark:hover:bg-slate-800/50 font-medium')
          "
        >
          <svg lucideDisc [size]="26" [strokeWidth]="rlaCol.isActive ? 2.5 : 2"></svg>
          <span class="mt-1.5 text-xs tracking-wide">Collection</span>
        </a>

        <!-- Stats -->
        <a
          routerLink="/statistics"
          routerLinkActive
          #rlaStats="routerLinkActive"
          [class]="
            'flex flex-col items-center justify-center py-4 px-2 w-[calc(100%-1rem)] rounded-2xl mx-2 transition-all duration-200 ' +
            (rlaStats.isActive
              ? 'text-indigo-600 dark:text-indigo-400 bg-indigo-50/50 dark:bg-indigo-900/20 shadow-sm font-bold'
              : 'text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-100/50 dark:hover:bg-slate-800/50 font-medium')
          "
        >
          <svg lucideBarChart2 [size]="26" [strokeWidth]="rlaStats.isActive ? 2.5 : 2"></svg>
          <span class="mt-1.5 text-xs tracking-wide">Stats</span>
        </a>

        <!-- Profile -->
        <a
          routerLink="/profile"
          routerLinkActive
          #rlaProfile="routerLinkActive"
          [class]="
            'flex flex-col items-center justify-center py-4 px-2 w-[calc(100%-1rem)] rounded-2xl mx-2 transition-all duration-200 ' +
            (rlaProfile.isActive
              ? 'text-indigo-600 dark:text-indigo-400 bg-indigo-50/50 dark:bg-indigo-900/20 shadow-sm font-bold'
              : 'text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-100/50 dark:hover:bg-slate-800/50 font-medium')
          "
        >
          <svg lucideUser [size]="26" [strokeWidth]="rlaProfile.isActive ? 2.5 : 2"></svg>
          <span class="mt-1.5 text-xs tracking-wide">Profile</span>
        </a>

        <!-- Scan Button -->
        <div class="px-3 mt-4 w-full">
          <button
            (click)="scanClick.emit()"
            class="flex flex-col items-center justify-center py-3.5 w-full bg-indigo-500 text-white rounded-2xl shadow-[0_8px_16px_-6px_rgba(79,70,229,0.5)] hover:bg-indigo-600 hover:-translate-y-1 transition-all duration-300 group cursor-pointer"
            aria-label="Scan Record"
          >
            <svg lucideScanLine [size]="24" class="group-hover:scale-110 transition-transform"></svg>
            <span class="mt-1.5 text-xs font-bold tracking-wide">Scan</span>
          </button>
        </div>
      </nav>

      <!-- Settings -->
      <button
        routerLink="/settings"
        routerLinkActive
        #rlaSettings="routerLinkActive"
        aria-label="Settings"
        [class]="
          'p-4 transition-colors rounded-xl hover:bg-slate-100/50 dark:hover:bg-slate-800/50 mb-2 cursor-pointer ' +
          (rlaSettings.isActive
            ? 'text-indigo-600 dark:text-indigo-400 bg-indigo-50/50 dark:bg-indigo-900/20'
            : 'text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-300')
        "
      >
        <svg lucideSettings [size]="24"></svg>
      </button>
    </aside>
  `,
})
export class SidebarComponent {
  readonly scanClick = output<void>();
}
